#ifndef _COMMON_H
#define _COMMON_H

enum {
	NO_ERROR = 0,
	ERROR_CANT_CREATE = 1,
	ERROR_CANT_BIND = 2,
	ERROR_CANT_LISTEN = 3,
	ERROR_CANT_ACCEPT = 4,
	ERROR_CANT_READ = 5,
	ERROR_CANT_CONNECT = 6,
	ERROR_CANT_SEND = 7,
	ERROR_INTERRUPTED = 100
};

#define MAX_MESSAGE_SIZE 2000
#define MAX_CLIENTS 10

#endif /* _COMMON_H */
